version: '3.8'

services:
  fastapi:
    build:
      context: .  # Change to the root directory where Dockerfile is located relative to docker-compose.yml
      dockerfile: app/Dockerfile.fastapi  # Path to the FastAPI Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      S3_FOLDER_PATH: ${S3_FOLDER_PATH}
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}

  streamlit:
    build:
      context: .  # Change to the root directory where Dockerfile is located relative to docker-compose.yml
      dockerfile: app/Dockerfile.streamlit  # Path to the Streamlit Dockerfile
    container_name: streamlit_container
    ports:
      - "8501:8501"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      S3_FOLDER_PATH: ${S3_FOLDER_PATH}
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}

networks:
  default:
    driver: bridge
